services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  frontend:
    image: cansefr/my-app:latest
    container_name: my-app
    restart: unless-stopped
    ports:
      - "80:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 5
      start_period: 10s