name: Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env.production
        run: |
          echo "VITE_APP_HOST=${{ secrets.VITE_APP_HOST }}" >> .env.production
          echo "VITE_APP_GIT_OWNER=${{ secrets.VITE_APP_GIT_OWNER }}" >> .env.production
          echo "VITE_APP_GIT_REPO=${{ secrets.VITE_APP_GIT_REPO }}" >> .env.production
          echo "VITE_APP_GIT_BEARER_PAT=${{ secrets.VITE_APP_GIT_BEARER_PAT }}" >> .env.production

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cansefr/my-app:latest
          platforms: linux/amd64

      - name: Upload compose to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.yaml"
          target: "/home/root/my-app"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -euo pipefail
            cd /home/root/my-app

            echo "==> Pull image"
            docker pull cansefr/my-app:latest

            echo "==> Compose up (idempotent)"
            docker compose up -d --remove-orphans

            echo "==> Healthcheck HTTP"
            for i in $(seq 1 30); do
              if curl -fsS "http://localhost/" >/dev/null; then
                echo "OK"
                exit 0
              fi
              sleep 2
            done
            echo "Healthcheck KO"; exit 1